flick_seeker/urls.py
from django.urls import path  # DjangoのURLパターンを定義するためのモジュールから、path関数をインポート
from django.contrib.auth import views as auth_views  # Djangoの認証システム関連のビューをインポート
from django.urls import path, include  # URLパス関連の機能をインポート
from .views import top, signup, login_view,  signup_complete, dashboard, movie_list, mypage, my_reviews, my_favorites,movie_register,movie_register_complete, movie_list, movie_detail, add_review, movie_detail_edit, review_vote, toggle_favorite, edit_review, all_movie_reviews, search_results, PasswordChangeView, PasswordChangeDoneView, delete_user, edit_profile, portfolio  # アプリケーションのビュー関数をインポート
from . import views

app_name = 'flick_seeker'  # アプリケーションの名前空間を設定

urlpatterns = [     
    path('top/', top, name='top'),  # '/top/' URL を 'top' ビューにマッピング
    path('signup/', signup, name='signup'),  # '/signup/' URL を 'signup' ビューにマッピング
    path('login/', login_view, name='login'),  # '/login/' URL を 'login_view' ビューにマッピング
    path('signup_complete/', signup_complete, name='signup_complete'),  # '/signup_complete/' URL を 'signup_complete' ビューにマッピング、トークンをパラメータとして受け取る
    path('dashboard/', dashboard, name='dashboard'),  # '/dashboard/' URL を 'dashboard' ビューにマッピング
    path('movies/', movie_list, name='movie_list'),  # '/movies/' URL を 'movie_list' ビューにマッピング
    path('mypage/', mypage, name='mypage'),  # '/mypage/' URL を 'mypage' ビューにマッピング
    path('my_reviews/', my_reviews, name='my_reviews'),  # '/my_reviews/' URL を 'my_reviews' ビューにマッピング
    path('my_favorites/', my_favorites, name='my_favorites'),  # '/my_favorites/' URL を 'my_favorites' ビューにマッピング
    path('logout/', auth_views.LogoutView.as_view(next_page='flick_seeker:top'), name='logout'),  # '/logout/' URL を Djangoのログアウトビューにマッピング、ログアウト後は 'top' ビューにリダイレクト
    path('movie_register/', movie_register, name='movie_register'),
    path('movie_register_complete/', movie_register_complete, name='movie_register_complete'),
    path('movie_list/', movie_list, name='movie_list'),
    path('movie_detail/<int:movie_id>/', movie_detail, name='movie_detail'),
    path('movie/<int:movie_id>/add_review/', add_review, name='add_review'),
    path('movie_detail_edit/<int:movie_id>/', movie_detail_edit, name='movie_detail_edit'), 
    path('review/<int:review_id>/vote/<str:vote_type>/', review_vote, name='review_vote'),
    path('movie/<int:movie_id>/toggle_favorite/', toggle_favorite, name='toggle_favorite'),
    path('edit_review/<int:review_id>/', edit_review, name='edit_review'),
    # path('movie_reviews/<int:movie_id>/', movie_reviews, name='movie_reviews'),
    path('all_movie_reviews/<int:movie_id>/', all_movie_reviews, name='all_movie_reviews'),
    path('search_results/', search_results, name='search_results'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('delete_user/', delete_user, name='delete_user'),
    path('edit_profile/', edit_profile, name='edit_profile'),
]

screen_speak/urls.py
from django.contrib import admin  # Djangoの管理サイト機能をインポート
from django.urls import path, include  # URLパターン定義のための関数をインポート
from django.conf import settings
from django.conf.urls.static import static
from flick_seeker.views import portfolio


urlpatterns = [
    path('admin/', admin.site.urls),  # Django管理サイトへのURLパターンを定義
    path('screen_speak/', include('flick_seeker.urls', namespace='flick_seeker')),  
    path('', portfolio, name='portfolio'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flick_seeker/models.py
from django.db import models  # Djangoのデータベースモデルを定義するためのモジュールをインポート
from django.contrib.auth.models import AbstractUser, BaseUserManager  # Djangoのユーザーモデル(AbstractUser)とユーザーマネージャ(BaseUserManager)をインポート
from django.utils.translation import gettext as _  # Djangoの翻訳関数をインポートし、gettextとして別名を付ける
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# カスタムユーザーマネージャを定義するクラス
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        """
        通常のユーザーアカウントを作成します。
        emailとusernameが必須です。
        """
        # ユーザー作成メソッド。email が無い場合はエラーを発生させる
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, **extra_fields):
        """
        スーパーユーザーアカウントを作成します。
        is_staffとis_superuserフラグがTrueに設定されます。
        """
        # スーパーユーザー作成メソッド。is_staff と is_superuser を強制的に True に設定
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, username, password, **extra_fields)

# ユーザーモデル
class User(AbstractUser):
    username = models.CharField(_('username'), max_length=150, unique=True, null=False)  # ユーザー名フィールド
    email = models.EmailField(_('email address'), unique=True)  # emailアドレスフィールド
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True, default='profile_images/default-thumbnail.png')  # プロフィール画像フィールド
    bio = models.TextField(_("Bio"), blank=True, null=True)  # 自己紹介文のフィールド
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('Updated at'))
    
    USERNAME_FIELD = 'email'  # ユーザー名としてemailを使用
    REQUIRED_FIELDS = ['username']  # 必須フィールドを設定

    objects = CustomUserManager()  # カスタムユーザーマネージャを使用
    
    def __str__(self):
        # ユーザーの文字列表現
        return self.email

# 映画モデル
class Movie(models.Model):
    title = models.CharField(max_length=255)  # タイトルフィールド
    plot = models.TextField()  # あらすじフィールド
    director = models.CharField(max_length=255)  # 監督フィールド
    cast = models.CharField(max_length=255)  # 出演者フィールド
    release_year = models.PositiveIntegerField()  # 公開年フィールド
    thumbnail = models.ImageField(upload_to='movie_thumbnails/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）
    updated_at = models.DateTimeField(auto_now=True)  # 更新日時（自動で現在の日時が設定され、更新時に更新される）
    
    def __str__(self):
        # 映画の文字列表現
        return self.title

# レビューモデル
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # ユーザー外部キー
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)  # 映画外部キー
    rating = models.DecimalField(max_digits=2, decimal_places=1, validators=[MinValueValidator(0.5), MaxValueValidator(5)])  # レーティングのフィールドをDecimalFieldに変更し、0.5刻みでの評価を許可
    title = models.CharField(max_length=255)  # レビュータイトルフィールドの追加
    comment = models.TextField()  # コメントフィールド
    spoiler = models.BooleanField(default=False)  # ネタバレありの場合はTrue、なしの場合はFalse
    good_count = models.PositiveIntegerField(default=0)  #Goodのためのフィールド
    bad_count = models.PositiveIntegerField(default=0)  #Badのためのフィールド
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）
    updated_at = models.DateTimeField(auto_now=True)  # 更新日時（自動で現在の日時が設定され、更新時に更新される）

    def __str__(self):
        # レビューの文字列表現
        return f'{self.user.username} - {self.movie.title}'

# ハッシュタグモデル
class Hashtag(models.Model):
    CATEGORY_CHOICES = (
        ('genre', 'ジャンル'),
        ('situation', 'シチュエーション'),
    )
    label = models.CharField(max_length=255)  # ラベルフィールド
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='genre')  # デフォルト値を設定
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）

    def __str__(self):
        # ハッシュタグの文字列表現
        return self.label

# レビューとハッシュタグの関連モデル
class ReviewHashtag(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)  # レビュー外部キー
    hashtag = models.ForeignKey(Hashtag, on_delete=models.CASCADE)  # ハッシュタグ外部キー
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）

    def __str__(self):
        # レビューとハッシュタグの関連の文字列表現
        return f'{self.review.user.username} - {self.hashtag.label}'

# お気に入り映画モデル
class FavoriteMovie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # ユーザー外部キー
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)  # 映画外部キー
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）

    class Meta:
        unique_together = ('user', 'movie')  # 同じ映画に対する重複したお気に入りを防止
        
    def __str__(self):
        # お気に入り映画の文字列表現
        return f'{self.user.username} - {self.movie.title}'

# レビューリアクションモデル
class ReviewReaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # ユーザー外部キー
    review = models.ForeignKey(Review, on_delete=models.CASCADE)  # レビュー外部キー
    rating_type = models.CharField(max_length=255)  # リアクションの種類フィールド
    created_at = models.DateTimeField(auto_now_add=True)  # 作成日時（自動で現在の日時が設定される）

flick_seeker/forms.py
from django import forms  # Djangoのフォーム機能をインポート
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, UserChangeForm
from django.contrib.auth import get_user_model  # 現在使用中のユーザーモデルを取得する関数をインポート
from django.core.exceptions import ValidationError  # フォームのバリデーションエラーを処理するための例外クラスをインポート
from django.utils.translation import gettext_lazy as _  # 国際化（多言語対応）のための翻訳機能をインポート
from .models import Movie, Review, Hashtag, User
import datetime

User = get_user_model()  # 現在アクティブなユーザーモデルを取得

class CustomUserCreationForm(UserCreationForm):
    # カスタムユーザー作成フォーム。UserCreationFormを拡張してカスタマイズ
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')  # メールアドレスフィールドを定義。ヘルプテキスト付き
    username = forms.CharField(max_length=150, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.')  # ユーザー名フィールドを定義。ヘルプテキスト付き
    
    class Meta:
        model = User  # このフォームが使用するモデル
        fields = ('username','email', 'password1', 'password2')  # フォームで使用するフィールド
        
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザー名'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'
        
class PasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)

class MovieForm(forms.ModelForm):
    release_year = forms.CharField(label='公開年', widget=forms.TextInput(attrs={'placeholder': '例: 2020'}), required=False)
    
    class Meta:
        model = Movie
        fields = ['title', 'plot', 'director', 'cast', 'release_year', 'thumbnail']  # 必要に応じてフィールドを調整
        labels = {
            'title': 'タイトル',
            'plot': 'あらすじ',
            'director': '監督',
            'cast': '出演者',
            'thumbnail': '映画のカバー画像',
        }
        widgets = {
            'title': forms.TextInput(attrs={'required': True}),
        }
    
    def clean_release_year(self):
        release_year = self.cleaned_data.get('release_year')

        # 年が数値であるかを検証
        try:
            release_year = int(release_year)
        except ValueError:
            raise ValidationError('公開年は数値で入力してください。')

        # 年が妥当な範囲内であるかを検証（例: 1900年から現在の年まで）
        if release_year < 1900 or release_year > datetime.date.today().year:
            raise ValidationError('無効な公開年です。')

        return release_year
    
class ReviewForm(forms.ModelForm):
    # ハッシュタグを複数選択するためのフィールド
    hashtags = forms.ModelMultipleChoiceField(
        queryset=Hashtag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    
    class Meta:
        model = Review
        fields = ['title', 'rating', 'spoiler', 'comment', 'hashtags']
        widgets = {
            'rating': forms.NumberInput(attrs={'step': 0.5, 'max': 5}),
            'comment': forms.Textarea(attrs={'rows': 4}),
            'spoiler': forms.CheckboxInput(),  # ネタバレフィールドのwidgetをカスタマイズ
        }
        
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        
class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_new_password1(self):
        old_password = self.cleaned_data.get('old_password')
        new_password1 = self.cleaned_data.get('new_password1')
        if old_password and new_password1:
            if old_password == new_password1:
                raise ValidationError(_('同じパスワードは設定できません。別のパスワードを設定してください。'), code='password_no_change')
        return new_password1
    
class UserDeleteConfirmForm(forms.Form):
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserDeleteConfirmForm, self).__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data['password']
        if not self.user.check_password(password):
            raise forms.ValidationError('パスワードが間違っています。')
        return password
    
class CustomUserChangeForm(UserChangeForm):
    password = None  # パスワードフィールドをフォームから除外

    class Meta:
        model = User
        fields = ('username', 'email', 'profile_image', 'bio')  # 編集可能なフィールド
        widgets = {
            'profile_image': forms.FileInput(),     
        }

flick_seeker/templates/add_review.html
{% extends 'base.html' %}

{% block content %}
  <h2>レビューを投稿する</h2>

  <div class="content-wrapper">
    <h3>{{ movie.title }}</h3>
    <form method="post" class="edit-review-form">
      {% csrf_token %}
      <div>
        <label for="id_title">レビュータイトル:</label>
        {{ form.title }}
      </div>
      <div>
        <label for="id_rating">評価:</label>
        {{ form.rating }}
      </div>
      <div>
        {{ form.spoiler }} ネタバレあり
      </div>
      <div>
        <label for="id_comment">本文:</label>
        {{ form.comment }}
      </div>
      <label for="hashtag-selection" style="font-weight: bold; margin-bottom: 10px; display: block;">
        映画のレビューに合わせて、関連するハッシュタグを選んでください。これにより、検索がしやすくなります。
      </label>

      <!-- タブ切り替えボタン -->
      <div class="button-group">
        <button type="button" onclick="showCategory('genre')">ジャンル</button>
        <button type="button" onclick="showCategory('situation')">シチュエーション</button>
      </div>

      <!-- ジャンルハッシュタグ -->
      <div id="genre-tags" class="hashtag-category" style="display:none;">
        {% for hashtag in genre_hashtags %}
          <div class="checkbox">
            <label>
              <input type="checkbox" name="hashtags" value="{{ hashtag.id }}">
              {{ hashtag.label }}
            </label>
          </div>
        {% endfor %}
      </div>

      <!-- シチュエーションハッシュタグ -->
      <div id="situation-tags" class="hashtag-category" style="display:none;">
        {% for hashtag in situation_hashtags %}
          <div class="checkbox">
            <label>
              <input type="checkbox" name="hashtags" value="{{ hashtag.id }}">
              {{ hashtag.label }}
            </label>
          </div>
        {% endfor %}
      </div>

      <div class="form-actions">
        <button type="submit">投稿</button>
      </div>
    </form>
  </div>

  <div class="navigation-buttons">
    <!-- 戻るボタンを追加 -->
    <a href="{% url 'flick_seeker:movie_detail' movie.id %}" class="btn btn-secondary">戻る</a>

    <!-- ホーム画面へのリンクボタン -->
    <br><a href="{% url 'flick_seeker:dashboard' %}" class="button">ホームへ</a></br>
  </div>

<!-- タブ切り替え用のJavaScript -->
<script>
  // タブ切り替え関数
  function showCategory(category) {
    console.log(category); // 確認のためのログ
    var genreTagsDiv = document.getElementById('genre-tags');
    var situationTagsDiv = document.getElementById('situation-tags');
    console.log(genreTagsDiv, situationTagsDiv); // これらの要素が正しく取得できているかを確認

    if (category === 'genre') {
      genreTagsDiv.style.display = 'block';
      situationTagsDiv.style.display = 'none';
    } else if (category === 'situation') {
      genreTagsDiv.style.display = 'none';
      situationTagsDiv.style.display = 'block';
    }
  }
</script>

{% endblock %}

flick_seeker/templates/movie_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="movie-detail-container">
    <h1>{{ movie.title }}</h1>
    {% if movie.thumbnail %}
      <img class="movie-detail-movie-image" src="{{ movie.thumbnail.url }}" alt="{{ movie.title }} Thumbnail">
    {% endif %}

    <div class="movie-detail-movie-info">  
      <p>平均評価: {{ average_rating }}</p> 
      <p class="movie-plot"><strong>あらすじ:</strong> {{ movie.plot }}</p>
      <p><strong>監督:</strong> {{ movie.director }}</p>
      <p><strong>出演者:</strong> {{ movie.cast }}</p>
      <p class="release-year"><strong>公開年:</strong> {{ movie.release_year }}</p>
    </div>
  </div>

  <!-- ユーザーが認証されている場合、編集ページへのリンクを表示 -->
  {% if request.user.is_authenticated %}
    <a href="{% url 'flick_seeker:movie_detail_edit' movie.id %}" class="button edit-movie-button">映画情報を編集</a>
  {% endif %}

  <!-- レビュー表示 -->
  <div class="movie-reviews-container">
    <h2>映画レビュー</h2>
    <!-- レビュー投稿リンク -->
    <a href="{% url 'flick_seeker:add_review' movie.id %}" class="button review-link">レビューを書く</a>

    <!-- 最初の3件のレビューのみを表示 -->
    {% for review in reviews|slice:":3" %} 
      <div class="review">
      <!-- ユーザーのアイコン表示 -->
        {% if review.user.profile_image %}
          <img src="{% if review.user.profile_image %}{{ review.user.profile_image.url }}{% else %}{{ MEDIA_URL }}default-thumbnail.png{% endif %}" alt="{{ review.user.username }}'s Profile Icon" style="width: 50px; height: 50px; border-radius: 50%;">
          <span>{{ review.user.username }}さん</span>
        {% endif %}
        <!-- レビュータイトルとユーザー名の表示 -->
        <p><strong>{{ review.title }}</strong></p> 
        <p>評価: {{ review.rating }}</p>
        {% if review.spoiler %}
          <!-- ネタバレがある場合、クリックして表示する -->
          <p class="spoiler">ネタバレあり: <a href="#" onclick="toggleSpoilerVisibility(this);return false;">内容を表示</a></p>
          <div class="spoiler-content" style="display:none;">{{ review.comment }}</div>
        {% else %}
          <!-- ネタバレがない場合、そのままコメントを表示 -->
          <p>{{ review.comment }}</p>
        {% endif %}

        <!-- ハッシュタグを表示するコードを追加 -->
        <p>ハッシュタグ:</p>
        <ul>
          {% for hashtag in review.hashtags %}
            <li>{{ hashtag.hashtag.label }}</li>
          {% endfor %}
        </ul>

        <button class="vote-button" data-review="{{ review.id }}" data-vote-type="good">Good: {{ review.good_count }}</button>
        <button class="vote-button" data-review="{{ review.id }}" data-vote-type="bad">Bad: {{ review.bad_count }}</button>
      </div>
    {% empty %}
      <p>レビューはありません。</p>
    {% endfor %}

    {% if reviews.count > 0 %}
      <a href="{% url 'flick_seeker:all_movie_reviews' movie.id %}" class="button all-movie-reviews">全ての映画レビューを表示する</a>
    {% endif %}

    <!-- お気に入りボタン -->
    <button type="button" id="favorite-button" data-url="{% url 'flick_seeker:toggle_favorite' movie_id=movie.id %}" data-favorited="{{ is_favorited|yesno:'true,false' }}">
      {{ is_favorited|yesno:'お気に入り済み,お気に入りに追加' }}
    </button>      
    
    <div class="auth-buttons">

      <!-- 前の画面に戻るボタン -->
      <a href="{% url 'flick_seeker:movie_list' %}" class="button back-button">映画一覧へ</a>

      <!-- ホーム画面へのリンクボタン -->
      <a href="{% url 'flick_seeker:dashboard' %}" class="button back-button">ホームへ</a>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
  <script>
    // Djangoテンプレートからmovie.idを取得する
    const movieId = "{{ movie.id }}";
  </script>

  <script>
    // お気に入りボタンのクリックイベント
    document.getElementById('favorite-button').addEventListener('click', function() {
      var button = this; // ボタンのDOM要素を取得
      var favorited = button.getAttribute('data-favorited') === 'true'; // お気に入り状態を取得
      var url = button.dataset.url; // URLを `data-url` 属性から取得
      
      // CSRFトークンを取得
      var csrfToken = getCookie('csrftoken');

      // AJAXリクエストを送信
      fetch(url, {
        method: 'POST',
        headers: {
          'X-CSRFToken': csrfToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ 'movie_id': movieId })
      })
      .then(response => response.json())
      .then(data => {
        // お気に入りの状態をトグル
        if (data.is_favorite) {
          button.classList.add('favorite-added');
          button.textContent = 'お気に入り済み';
        } else {
          button.classList.remove('favorite-added');
          button.textContent = 'お気に入りに追加';
        }
        button.setAttribute('data-favorited', data.is_favorite.toString());
      })
      .catch(error => console.error('Error:', error));
    });

    // ページの読み込みが完了した後に実行されるイベントリスナー
    document.addEventListener('DOMContentLoaded', (event) => {
      const favoriteButton = document.getElementById('favorite-button');
      const isFavorited = favoriteButton.getAttribute('data-favorited') === 'true';
  
      // お気に入り状態に応じてクラスを設定する
      if (isFavorited) {
        favoriteButton.classList.add('favorite-added');
        favoriteButton.textContent = 'お気に入り済み';
      } else {
        favoriteButton.classList.remove('favorite-added');
        favoriteButton.textContent = 'お気に入りに追加';
      }
    });

    // Good/BadボタンのAjaxリクエスト
    document.querySelectorAll('.vote-button').forEach(button => {
        console.log("投票ボタンが設定されました:", button); // 各ボタンのログ
        button.addEventListener('click', function() {
            console.log("Vote button clicked", this);
            // 投票ボタンを無効にする処理
            disableOppositeButton(this);
            
            const reviewId = this.dataset.review;
            const voteType = this.dataset.voteType;
            fetch(`/review/${reviewId}/vote/${voteType}/`, {
                method: 'POST',
                headers: {'X-CSRFToken': getCookie('csrftoken')},
            })
            .then(response => response.json())
            .then(data => {
                console.log("投票のレスポンス:", data); // レスポンスのログ
                // 投票カウントの更新
                updateVoteCount(this, data);
                // 逆のボタンを再度有効にする処理   
                enableOppositeButton(this);
            });
        });
    });

    // 逆のボタンを無効にする関数
    function disableOppositeButton(clickedButton) {
        let oppositeVoteType = clickedButton.dataset.voteType === 'good' ? 'bad' : 'good';
        let oppositeButton = clickedButton.parentElement.querySelector(`[data-vote-type=${oppositeVoteType}]`);
        if (oppositeButton) {
            oppositeButton.disabled = true;
        }
    }

    // 逆のボタンを有効にする関数
    function enableOppositeButton(clickedButton) {
        let oppositeVoteType = clickedButton.dataset.voteType === 'good' ? 'bad' : 'good';
        let oppositeButton = clickedButton.parentElement.querySelector(`[data-vote-type=${oppositeVoteType}]`);
        if (oppositeButton) {
            oppositeButton.disabled = false;
        }
    }

    // ボタンのテキストを更新する関数
    function updateVoteCount(button, data) {
        // レスポンスから取得したgood_countとbad_countを使用してカウントを更新
        if ('good_count' in data && 'bad_count' in data) {
            // 対応するボタンを見つける
            let goodButton = button.parentElement.querySelector('[data-vote-type="good"]');
            let badButton = button.parentElement.querySelector('[data-vote-type="bad"]');
            // ボタンのテキストを新しいカウントで更新
            goodButton.textContent = `Good: ${data.good_count}`;
            badButton.textContent = `Bad: ${data.bad_count}`;
        } else {
            // 応答データに必要なプロパティがない場合はエラーをログに記録
            console.error('Good count or Bad count is missing from the response', data);
        }
    }

    // CSRFトークン取得のためのヘルパー関数
    function getCookie(name) {
        console.log("CSRFトークンを取得します:", name); // トークン取得のログ
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        console.log("取得したCSRFトークン:", cookieValue); // 取得したトークンのログ
        return cookieValue;
    }

    function toggleSpoilerVisibility(link) {
      var spoilerContent = link.parentNode.nextElementSibling;
      if (spoilerContent.style.display === 'none') {
        spoilerContent.style.display = 'block';
        link.textContent = '内容を隠す';
      } else {
        spoilerContent.style.display = 'none';
        link.textContent = '内容を表示';
      }
    }

  </script>


  
{% endblock %}